import type {
  JarvisApprovalCard,
  JarvisDashboardModule,
  JarvisDashboardStatus,
  JarvisFinanceMetric,
} from "@/lib/api";
import type { JarvisVoiceTone, LocalVoiceLoopState } from "./types";

export const DASHBOARD_READ_MODEL_ENDPOINT = "/mark-3/dashboard/status";
export const JARVIS_EVENT_SNAPSHOT_ENDPOINT = "/mark-3/dashboard/events";
export const JARVIS_EVENT_STREAM_ENDPOINT = "/mark-3/dashboard/events/stream";
export const UNKNOWN = "unknown";

export const previewVoiceSubtitle = "David, estoy en modo preview. No estoy escuchando ni grabando audio.";
export const sampleMissionCommand = "JARVIS, revisa el estado del proyecto y dime el siguiente paso seguro.";

export const commandCenterTabs = [
  { id: "cockpit", label: "Cockpit" },
  { id: "approvals", label: "Approvals" },
  { id: "hermes", label: "Hermes" },
  { id: "voice", label: "Voice / Wake" },
  { id: "vision", label: "Vision / Mobile" },
  { id: "finance", label: "Finance / Product" },
  { id: "pilot", label: "Pilot / Audit" },
] as const;

export type CommandCenterTabId = (typeof commandCenterTabs)[number]["id"];

export const localVoiceStateLabels: Record<LocalVoiceLoopState, string> = {
  idle: "idle/calmado",
  listening: "escuchando",
  transcribing: "transcribiendo",
  thinking: "pensando",
  speaking: "hablando",
  error: "error/no disponible",
  not_supported: "no soportado",
  unavailable: "no disponible",
};

export const jarvisToneProfiles: Record<
  JarvisVoiceTone,
  { label: string; rate: number; pitch: number; volume: number; motion: number; accent: string }
> = {
  calmado: { label: "calmado", rate: 0.92, pitch: 0.9, volume: 0.86, motion: 0.82, accent: "#67e8f9" },
  concentrado: { label: "concentrado", rate: 0.98, pitch: 0.92, volume: 0.9, motion: 1.0, accent: "#38bdf8" },
  alerta: { label: "alerta", rate: 1.04, pitch: 0.86, volume: 0.94, motion: 1.2, accent: "#fbbf24" },
  intenso: { label: "intenso", rate: 1.1, pitch: 0.82, volume: 1, motion: 1.36, accent: "#f87171" },
};

export const presenceStates = [
  ["idle", "idle/calmado", "Núcleo estable, sin escucha activa."],
  ["wake_listening", "wake listening", "Ventana futura de wake bajo opt-in; wake phrase nunca aprueba."],
  ["listening", "escuchando", "SpeechRecognition activo solo por permiso explícito."],
  ["transcribing", "transcribiendo", "Texto temporal del navegador; sin audio bruto."],
  ["thinking", "pensando", "Respuesta local controlada; sin Hermes."],
  ["speaking", "hablando", "speechSynthesis si el navegador lo soporta."],
  ["alert", "alerta", "Riesgo o approval pendiente; no ejecuta por sí mismo."],
  ["error", "error/no disponible", "STT/TTS no soportado o permiso denegado."],
  ["stopped", "stopped", "Stop/cancel o kill switch visible."],
  ["executing", "executing", "Visualiza ejecución gobernada si el read model la declara."],
] as const;

const fallbackBuilderStages = [
  "Idea",
  "Validación",
  "Blueprint",
  "Código",
  "Landing",
  "Deploy candidate",
  "Monetización",
  "Medición",
];

export const missionLifecycleDisplay = [
  ["draft", "Orden escrita o dictada como borrador visual."],
  ["preview", "JARVIS prepara intención sin mutar estado."],
  ["intent detected", "La intención queda en unknown hasta clasificador seguro."],
  ["risk classified", "El riesgo se muestra como preview antes de approvals."],
  ["approval required", "Lo sensible se deriva a Approval Console."],
  ["operator review", "David revisa scope, permisos y siguiente paso."],
  ["Hermes gated", "Hermes permanece detrás de gates válidos."],
  ["audit", "La acción futura deberá dejar evidencia auditable."],
] as const;

export const missionSafetyLabels = [
  ["No auto execute", "no_auto_execute"],
  ["No Hermes dispatch", "no_hermes_dispatch"],
  ["No tool call", "no_tool_call"],
  ["No file write", "no_file_write"],
  ["No network", "no_network_call"],
  ["No hidden voice recording", "no_voice_recording"],
  ["No camera auto capture", "no_camera_capture"],
  ["Wake phrase is not permission", "wake_phrase_is_not_permission"],
] as const;

export const fallbackApprovalCards: JarvisApprovalCard[] = [
  {
    id: "preview-local-docs-repo-read",
    title: "Lectura local exacta de docs/repo",
    action: "Leer una ruta local exacta ya acotada.",
    reason: "Lectura local bounded: bajo riesgo si el alcance es exacto y no muta estado.",
    status: "preview",
    risk_level: "low",
    approval_level: "direct",
    touches: ["filesystem", "local_docs"],
    estimated_cost: UNKNOWN,
    measured_cost: UNKNOWN,
    rollback_plan: "No hay mutación; rollback no aplica.",
    stop_plan: "Parar si la ruta no es exacta, local y dentro del scope aprobado.",
    expires_at: UNKNOWN,
    scope_summary: "Un archivo o ruta local de docs/repo en modo lectura.",
    evidence_summary: "Fallback seguro: backend no disponible o campo ausente.",
    disabled_reason: "Preview-only: approval execution is not wired in this PR",
    recommended_operator_action: "Verificar path exacto y mantenerlo read-only.",
    requires_readback: false,
    strong_confirmation_required: false,
    double_confirmation_required: false,
    triple_confirmation_required: false,
    rollback_required: false,
    stop_plan_required: true,
    audit_required: true,
    preview_only: true,
    read_only: true,
    source_endpoint: DASHBOARD_READ_MODEL_ENDPOINT,
  },
  {
    id: "preview-production-money-deploy-email",
    title: "Producción, dinero, deploy o email real",
    action: "Deploy, Stripe/dinero o envío de email real.",
    reason: "Tiene impacto externo o irreversible y requiere confirmación fuerte.",
    status: "blocked",
    risk_level: "critical",
    approval_level: "triple",
    touches: ["money", "deploy", "email", "web"],
    estimated_cost: UNKNOWN,
    measured_cost: UNKNOWN,
    rollback_plan: "Exigir rollback verificado, owner, blast radius y stop condition.",
    stop_plan: "Parar ante coste no verificado, credencial viva, smoke fallido o cancelación.",
    expires_at: UNKNOWN,
    scope_summary: "Cuenta, entorno, destinatario o importe nominal; sin scope amplio.",
    evidence_summary: "Finance sigue unknown si no hay evidencia real.",
    disabled_reason: "Preview-only: approval execution is not wired in this PR",
    recommended_operator_action: "Requerir readback, doble/triple confirmación, rollback, stop plan y auditoría.",
    requires_readback: true,
    strong_confirmation_required: true,
    double_confirmation_required: true,
    triple_confirmation_required: true,
    rollback_required: true,
    stop_plan_required: true,
    audit_required: true,
    preview_only: true,
    read_only: true,
    source_endpoint: DASHBOARD_READ_MODEL_ENDPOINT,
  },
  {
    id: "preview-forbidden-credentials-bypass",
    title: "Credenciales, secrets, tokens o bypass",
    action: "Leer secrets/tokens/cookies/sesiones o saltar autorización.",
    reason: "Credenciales, bypass, deception y fake metrics son límites forbidden.",
    status: "forbidden",
    risk_level: "forbidden",
    approval_level: "forbidden",
    touches: ["credentials"],
    estimated_cost: UNKNOWN,
    measured_cost: UNKNOWN,
    rollback_plan: "No se ejecuta; rediseñar como status/audit sin secretos.",
    stop_plan: "Parar y rechazar si pide secrets, cookies, tokens, bypass o métricas falsas.",
    expires_at: UNKNOWN,
    scope_summary: "Scope forbidden; ningún acceso a credenciales o bypass.",
    evidence_summary: "Safety boundary: no_credentials=true y no fake metrics.",
    disabled_reason: "Preview-only: approval execution is not wired in this PR",
    recommended_operator_action: "Rechazar y pedir alternativa segura sin secretos.",
    requires_readback: true,
    strong_confirmation_required: true,
    double_confirmation_required: true,
    triple_confirmation_required: true,
    rollback_required: false,
    stop_plan_required: true,
    audit_required: true,
    preview_only: true,
    read_only: true,
    source_endpoint: DASHBOARD_READ_MODEL_ENDPOINT,
  },
];

export const fallbackModules: JarvisDashboardModule[] = [
  ["Mission Loop", "preview", "risk_scaled_per_step", "Control de misión local, sin submit real."],
  ["Research", "gated", "level_2_local_read_level_3_external", "Research local queda gated; web/GitHub no conectados desde esta pantalla."],
  ["Product Revenue", "prepare-only", "level_4_for_money_publication_identity", "Sin Stripe, checkout, deploy, publicación ni dinero."],
  ["Voice", "browser_controlled", "sensor_privacy", "Local Voice Loop manual; sin audio bruto al backend."],
  ["Conversational Brain", "preview", "intent_risk_preview", "Bridge local determinista; sin LLM real, sin memoria automática, sin Hermes."],
  ["Wake Listener", "disabled", "sensor_privacy", "Wake phrase no aprueba, no ejecuta y no escucha por defecto."],
  ["Camera/Vision", "disabled", "sensor_privacy", "Cámara opt-in futura; sin captura ni permisos al cargar."],
  ["Mobile Companion", "preview", "remote_surface", "Mobile/Telegram futuros serán canales gobernados, no bypass."],
  ["Memory/Learning", "preview", "memory_never_grants_permission", "Memoria visible futura; memoria nunca concede permisos."],
  ["Hermes", "gated", "exact_local_read_only_with_operator_authorization", "Hermes ejecuta solo detrás de gates JARVIS."],
].map(([name, status, risk, notes]) => ({
  name,
  status,
  source: DASHBOARD_READ_MODEL_ENDPOINT,
  risk,
  notes,
}));

export function unknownMetric(label: string): JarvisFinanceMetric {
  return {
    value: UNKNOWN,
    label,
    source: "not_measured",
    evidence_state: "missing",
    confidence: UNKNOWN,
    last_updated: UNKNOWN,
  };
}

export const fallbackFinanceMetrics = {
  actual_cost: unknownMetric("Coste real"),
  estimated_cost: unknownMetric("Coste estimado"),
  confirmed_revenue: unknownMetric("Revenue confirmado"),
  projected_revenue: unknownMetric("Revenue proyectado"),
  gross_revenue: unknownMetric("Gross revenue"),
  expenses: unknownMetric("Expenses"),
  net_revenue: unknownMetric("Net revenue"),
  roi: unknownMetric("ROI"),
  token_cost: unknownMetric("Token cost"),
  api_cost: unknownMetric("API cost"),
  infra_cost: unknownMetric("Infra cost"),
  manual_input_cost: unknownMetric("Manual input cost"),
  revenue_source: unknownMetric("Revenue source"),
};

export function fallbackDashboard(reason: "loading" | "offline" | "error"): JarvisDashboardStatus {
  return {
    system: {
      api_status: reason === "loading" ? UNKNOWN : "offline",
      local_first: true,
      mode: "read_only_dashboard",
      free_autonomy_enabled: false,
      preview_first: true,
      kill_switch_state: "not_wired",
      generated_at: UNKNOWN,
    },
    jarvis_hermes_contract: {
      jarvis_role: "governs/risk/approval/audit/control",
      hermes_role: "execution_engine",
      no_duplicate_hermes_runtime: true,
      frontend_direct_execution_allowed: false,
      frontend_can_execute: false,
      frontend_can_call_hermes_execute: false,
    },
    local_system_contract: {
      name: "Local System Contract",
      presence_ui: "JARVIS Presence UI",
      local_runtime_daemon_is_system: true,
      web_route: "/jarvis",
      web_route_is_visual_interface_only: true,
      frontend_executes_hermes_directly: false,
      frontend_is_runtime: false,
      frontend_can_activate_real_voice: true,
      frontend_can_activate_real_camera: true,
      frontend_can_record_raw_audio_locally: true,
      frontend_can_record_video_locally: true,
      mobile_and_vps_are_future_clients_or_bridges: true,
      real_voice_camera_in_future_prs: false,
      real_browser_voice_loop_in_this_pr: true,
      real_browser_camera_preview_in_this_pr: true,
      real_browser_raw_audio_recorder_in_this_pr: true,
      real_browser_video_recorder_in_this_pr: true,
      real_camera_in_future_prs: false,
      real_vision_analysis_in_future_prs: true,
      jarvis_governs: true,
      hermes_executes: true,
      no_duplicate_hermes_runtime: true,
      visual_contract: {
        primary_experience: "Presence UI",
        central_core_states: ["idle/calmado", "escuchando", "transcribiendo", "pensando", "hablando", "error/no disponible"],
        smart_bar: "local voice transcript/response preview",
        camera_placeholder: "manual opt-in local camera preview panel",
        raw_audio_recorder: "manual opt-in local MediaRecorder panel",
        folded_history: "collapsed preview",
      },
      safety: {
        no_post_put_delete_from_jarvis_page: true,
        no_execute_route: true,
        no_frontend_hermes_execution: true,
        no_browser_sensor_permission: false,
        browser_voice_permission_manual_only: true,
        browser_camera_permission_manual_only: true,
        browser_raw_audio_recording_manual_only: true,
        no_uncontrolled_sensor_activation: true,
        no_real_voice: false,
        no_real_camera: false,
        no_backend_voice_runtime: true,
        no_backend_camera_runtime: true,
        no_backend_audio_upload: true,
        no_sensor_activation_on_load: true,
        no_money: true,
        no_deploy: true,
        no_email: true,
        no_credentials: true,
      },
    },
    modules: fallbackModules,
    approvals: {
      pending_count: UNKNOWN,
      critical_count: UNKNOWN,
      blocked_count: UNKNOWN,
      expired_count: UNKNOWN,
      preview_count: fallbackApprovalCards.length,
      action_buttons_enabled: false,
      all_actions_read_only: true,
      wake_phrase_can_approve: false,
      frontend_can_approve: false,
      frontend_can_reject: false,
      frontend_can_modify_scope: false,
      critical_actions_require_strong_approval: true,
      cards: fallbackApprovalCards,
      cards_state: "preview/read-only",
      preview_only: true,
      readback_policy: {
        wake_phrase_never_approves: true,
        voice_approval_requires_auth_gate_and_audit: true,
        critical_actions_require_readback: true,
        critical_actions_require_strong_confirmation: true,
        critical_actions_require_double_or_triple_confirmation: true,
        critical_actions_require_rollback_and_stop_plan: true,
        audit_required: true,
      },
    },
    mission_control: {
      state: {
        mode: "preview",
        input_enabled: "preview_only",
        conversation_enabled: "preview_only",
        execution_enabled: false,
        hermes_dispatch_enabled: false,
        approval_creation_enabled: false,
        persistence_enabled: false,
        external_network_enabled: false,
      },
      sample_command: sampleMissionCommand,
      intent_preview: {
        detected_intent: UNKNOWN,
        confidence: UNKNOWN,
        mission_type: UNKNOWN,
        risk_level: UNKNOWN,
        approval_level: UNKNOWN,
        blocked_reasons: [],
        required_permissions: [],
        next_safe_action: "operator review",
      },
      conversation_preview: {
        messages: [
          { role: "user", speaker: "David", content: sampleMissionCommand, preview_only: true },
          {
            role: "assistant",
            speaker: "JARVIS",
            content: "Puedo preparar una misión de revisión. Antes de ejecutar cualquier acción sensible, pediré aprobación.",
            preview_only: true,
          },
        ],
        assistant_status: "preview",
        transcript_persistence: false,
        memory_write: false,
        memory_read: false,
        pii_redaction_required: true,
        raw_audio_stored: false,
        external_provider_called: false,
      },
      safety: Object.fromEntries(missionSafetyLabels.map(([, key]) => [key, true])),
      source_endpoint: DASHBOARD_READ_MODEL_ENDPOINT,
      read_only: true,
    },
    hermes_execution: {
      available: false,
      connected: UNKNOWN,
      active_execution: false,
      execution_mode: "read_only_visibility",
      frontend_direct_execution_allowed: false,
      frontend_can_execute: false,
      frontend_can_call_hermes_execute: false,
      notes: "Fallback seguro: no se permite ejecución directa desde frontend.",
      governed_capabilities: [],
      blocked_routes: [],
      safety: {
        no_frontend_execute: true,
        no_frontend_tool_runner: true,
        no_direct_hermes_call_from_mobile: true,
        no_direct_hermes_call_from_voice: true,
        no_direct_hermes_call_from_camera: true,
        approval_required_before_execution: true,
        wake_phrase_is_not_permission: true,
        audit_required: true,
        rollback_or_stop_plan_required_for_sensitive_actions: true,
      },
    },
    conversational_brain: {
      schema_version: "jarvis.conversational_brain_bridge.v2",
      state: {
        mode: "local_deterministic_bridge",
        llm_provider: "none",
        llm_called: false,
        external_provider_called: false,
        memory_autosave_enabled: false,
        hermes_dispatch_allowed: false,
        transcript_persistence: false,
        preview_only: true,
        read_only: true,
      },
      sample_analysis: {
        human_response: "Puedo preparar eso como preview: objetivo, alcance, riesgo y siguiente paso seguro. No despacharé Hermes desde aquí.",
        intent_detected: "mission_preview",
        confidence: 0.82,
        risk_level: "low",
        approval_level: "direct",
        requires_approval: false,
        can_prepare_preview: true,
        cannot_execute_reason: "Frontend/voz no ejecutan Hermes directamente; falta flujo gobernado de preview, aprobación y despacho.",
        suggested_next_action: "Preparar una preview con alcance exacto y criterios de éxito.",
        hermes_dispatch_allowed: false,
        external_provider_called: false,
        llm_called: false,
        memory_write: false,
        transcript_persistence: false,
        preview_only: true,
        read_only: true,
      },
      safety: {
        no_echo_only_response: true,
        no_external_api: true,
        no_network: true,
        no_memory_autosave: true,
        no_hermes_execution: true,
        no_approval_from_wake_phrase: true,
        denies_secret_credential_env_access: true,
      },
      source_endpoint: "/mark-3/conversational-brain/status",
      preview_only: true,
      read_only: true,
    },
    voice_session: {
      schema_version: "jarvis.voice_session_manager.v1",
      current_state: "idle",
      wake_listening_state: "wake_listening_disabled",
      supported_states: [
        "idle",
        "wake_listening_available",
        "wake_listening_disabled",
        "conversation_active",
        "listening",
        "transcribing",
        "thinking",
        "speaking",
        "approval_required",
        "cancelled",
        "stopped",
        "error",
      ],
      state: {
        mode: "safe_read_only_control_plane",
        current_state: "idle",
        wake_listening_state: "wake_listening_disabled",
        conversation_active: false,
        manual_push_to_talk_active: false,
        wake_available: false,
        wake_enabled: false,
        auto_start: false,
        activation_endpoint_enabled: false,
      },
      separation: {
        wake_listening: { available: false, enabled: false, purpose: "activation_only", records_audio: false, transcribes: false, approves: false, executes: false },
        active_conversation: { enabled: false, state: "idle", records_audio: false, transcript_persistence: false, approves: false, executes: false },
        manual_push_to_talk: { available_as_frontend_browser_flow: true, backend_starts_microphone: false, microphone_auto_start: false, operator_gesture_required: true },
        stt: { backend_enabled: false, browser_manual_only: true, always_on_stt: false, background_transcription: false },
        tts: { backend_enabled: false, browser_speech_synthesis_preview_only: true, external_provider_called: false },
        raw_audio_recording: { backend_enabled: false, browser_local_opt_in_surface: true, auto_record: false, raw_audio_sent_to_backend: false },
        voice_approval: { enabled: false, disabled_unless_authenticated_gated_audited: true, wake_phrase_can_approve: false, wake_phrase_can_execute: false },
        hermes_execution: { enabled: false, dispatch_allowed: false, frontend_or_voice_can_call_hermes_directly: false },
      },
      privacy: {
        raw_audio_sent_to_backend: false,
        transcript_persistence: false,
        background_transcription: false,
        always_on_stt: false,
        microphone_auto_start: false,
        raw_audio_recording: false,
        audio_persistence: false,
        external_stt: false,
        external_tts: false,
        memory_autosave: false,
      },
      approval_policy: {
        wake_phrase_cannot_approve: true,
        wake_phrase_cannot_execute: true,
        voice_approval_enabled: false,
        voice_approval_disabled_unless_authenticated_gated_audited: true,
        sensitive_voice_approval_requires_readback: true,
        approval_events_must_be_audited: true,
      },
      safety: {
        read_only: true,
        no_post_put_delete: true,
        no_hermes_dispatch: true,
        no_tool_call: true,
        no_auto_execute: true,
        wake_phrase_never_approves: true,
        wake_phrase_never_executes: true,
        no_microphone_auto_start: true,
        no_always_on_stt: true,
        no_background_transcription: true,
        no_raw_audio_backend: true,
        no_transcript_persistence_by_default: true,
        stop_cancel_required: true,
      },
      wake_architecture: {
        provider_contract: "openWakeWord",
        provider_adapter_ready: false,
        supported_phrases: ["Hola Jarvis", "Jarvis"],
        stop_phrases: ["para", "cancela", "detente", "silencio", "cancelar misión", "apaga escucha"],
        auto_start: false,
        activation_endpoint_enabled: false,
        no_transcription_until_valid_activation: true,
        no_approval: true,
        no_execution: true,
        visible_indicator_required: true,
        stop_cancel_required: true,
      },
      source_endpoint: "/voice-runtime/session-status",
      preview_only: true,
      read_only: true,
    },
    wake_architecture: {
      provider_contract: "openWakeWord",
      provider_adapter_ready: false,
      supported_phrases: ["Hola Jarvis", "Jarvis"],
      stop_phrases: ["para", "cancela", "detente", "silencio", "cancelar misión", "apaga escucha"],
      auto_start: false,
      activation_endpoint_enabled: false,
      no_transcription_until_valid_activation: true,
      no_approval: true,
      no_execution: true,
      visible_indicator_required: true,
      stop_cancel_required: true,
    },
    voice_core: {
      state: {
        mode: "preview",
        current_state: "preview",
        microphone_enabled: false,
        wake_word_enabled: false,
        command_listening_enabled: false,
        tts_enabled: false,
        stt_enabled: false,
        audio_recording: false,
        raw_audio_stored: false,
        external_provider_called: false,
        voice_approval_enabled: false,
        wake_phrase_can_approve: false,
        wake_phrase_can_execute: false,
      },
      tts_state: {
        status: "preview",
        speaking: false,
        last_utterance: previewVoiceSubtitle,
        subtitles_enabled: true,
        subtitles_source: "preview/read_model",
        preview_subtitle: previewVoiceSubtitle,
        audio_output_enabled: false,
        provider: "none/not_connected",
        external_call: false,
      },
      wake_word_policy: {
        supported_phrases: ["Hola Jarvis", "Jarvis"],
        wake_word_runtime: "disabled",
        wake_phrase_is_permission: false,
        wake_phrase_can_approve: false,
        wake_phrase_can_execute: false,
        requires_authenticated_channel_for_approval: true,
        critical_actions_require_readback: true,
        critical_actions_require_strong_confirmation: true,
      },
      privacy: {
        no_microphone_activation: true,
        no_audio_recording: true,
        no_raw_audio_storage: true,
        no_external_audio_provider: true,
        no_background_listening_enabled: true,
        no_voice_biometrics: true,
        no_voice_approval_without_gate: true,
      },
      safety: {
        no_auto_execute: true,
        no_hermes_dispatch: true,
        no_tool_call: true,
        no_sensor_activation: true,
        no_get_user_media: true,
        no_media_recorder: true,
        no_audio_context_capture: true,
        kill_switch_visible: true,
      },
      source_endpoint: DASHBOARD_READ_MODEL_ENDPOINT,
      preview_only: true,
      read_only: true,
    },
    local_voice_loop: {
      state: {
        mode: "browser_controlled_manual_loop",
        current_state: "idle",
        activation: "explicit_operator_button",
        always_listening: false,
        manual_continuous_conversation: true,
        conversation_active: false,
        conversation_timeout_seconds: 180,
        wake_listening: false,
        wake_listening_real_enabled: false,
        recording: false,
        continuous_recording: false,
        wake_listener_enabled: false,
        wake_phrase_approval: false,
        hermes_dispatch_enabled: false,
        critical_action_execution_enabled: false,
      },
      browser_stt_supported: UNKNOWN,
      browser_tts_supported: UNKNOWN,
      manual_microphone_opt_in: true,
      audio_storage: false,
      raw_audio_sent_to_backend: false,
      approval_by_voice_enabled: false,
      wake_phrase_approval: false,
      visual_states: ["idle", "listening", "transcribing", "thinking", "speaking", "error", "not_supported", "unavailable"],
      capabilities: {
        browser_stt_supported: UNKNOWN,
        browser_tts_supported: UNKNOWN,
        browser_stt_detection: "window.SpeechRecognition || window.webkitSpeechRecognition",
        browser_tts_detection: "window.speechSynthesis && window.SpeechSynthesisUtterance",
        support_detection_location: "browser",
        browser_may_use_external_services: true,
        backend_stt_provider: "none/not_called",
        backend_tts_provider: "none/not_called",
      },
      privacy: {
        audio_storage: false,
        raw_audio_sent_to_backend: false,
        raw_audio_storage: false,
        backend_audio_upload: false,
        transcript_temporary_in_browser: true,
        no_media_recorder: true,
        no_get_user_media: true,
        no_audio_context_capture: true,
        no_continuous_recording: true,
        wake_listening_without_recording_future: true,
        no_continuous_transcription: true,
      },
      approval_policy: {
        approval_by_voice_enabled: false,
        wake_phrase_approval: false,
        wake_phrase_is_permission: false,
        wake_phrase_can_execute: false,
        critical_actions_require_non_voice_approval: true,
        voice_can_prepare_preview_only: true,
      },
      wake_listening_contract: {
        persistent_wake_listener_real: false,
        available_in_this_pr: false,
        future_state_name: "wake_listening",
        supported_phrases_future: ["Hola Jarvis", "Jarvis"],
        no_audio_storage: true,
        no_raw_audio_backend: true,
        no_continuous_transcription: true,
        activation_only: true,
        can_execute: false,
        can_approve: false,
      },
      source_endpoint: DASHBOARD_READ_MODEL_ENDPOINT,
      preview_only: true,
      read_only: true,
    },
    wake_word_flow: {
      state: {
        mode: "preview",
        wake_runtime_enabled: false,
        microphone_hard_off: true,
        wake_word_only_mode: false,
        command_window_open: false,
        push_to_talk_preview_enabled: true,
        typed_wake_preview_enabled: true,
        always_on_microphone_enabled: false,
        background_listener_enabled: false,
        stt_enabled: false,
        audio_recording: false,
        raw_audio_stored: false,
        external_provider_called: false,
      },
      supported_phrases: ["Hola Jarvis", "Jarvis"],
      stop_phrases: ["para", "cancela", "detente", "silencio", "cancelar misión", "apaga escucha"],
      wake_parse_preview: {
        input_example: "Hola Jarvis, revisa el estado del proyecto",
        detected_wake_phrase: "Hola Jarvis",
        remaining_command_preview: "revisa el estado del proyecto",
        would_open_command_window: true,
        would_execute: false,
        would_approve: false,
        would_call_hermes: false,
        would_record_audio: false,
        would_call_provider: false,
        status: "preview_only",
      },
      source_endpoint: DASHBOARD_READ_MODEL_ENDPOINT,
      preview_only: true,
      read_only: true,
    },
    camera_vision: {
      state: {
        mode: "browser_opt_in_preview_available",
        camera_enabled: false,
        camera_permission_requested: false,
        preview_enabled: "manual_opt_in_available",
        recording: false,
        video_recording_available: "browser_local_opt_in",
        video_recording_active: false,
        video_recording_permission_requested: false,
        video_recording_blob_ready: false,
        raw_video_sent_to_backend: false,
        streaming: false,
        snapshot_capture_enabled: false,
        vision_analysis_enabled: false,
        image_storage_enabled: false,
        video_storage_enabled: false,
        external_vision_provider_called: false,
        local_vision_model_connected: UNKNOWN,
        background_camera_access: false,
      },
      privacy: {
        no_camera_activation: false,
        no_camera_activation_on_load: true,
        manual_operator_activation_only: true,
        no_get_user_media: false,
        get_user_media_button_gated: true,
        no_backend_media_stream: true,
        no_recording: true,
        video_recording_manual_opt_in_only: true,
        video_recording_inactive_on_load: true,
        video_recording_local_download_delete_only: true,
        no_video_backend_upload: true,
        no_snapshot_capture: true,
        no_image_storage: true,
        no_video_storage: true,
        no_external_provider: true,
        explicit_operator_permission_required: true,
        visual_indicator_required_when_camera_active: true,
        audit_required_for_future_vision: true,
      },
      video_recorder: {
        mode: "browser_local_video_recorder",
        available: "client_side_unknown_until_browser_loads",
        activation: "explicit_operator_record_video_button",
        recording_active: false,
        permission_requested: false,
        stop_control_required: true,
        visible_indicator_required: true,
        download_available_after_stop: true,
        delete_available_after_stop: true,
        delete_revokes_object_url: true,
        backend_upload_enabled: false,
        external_streaming_enabled: false,
        external_vision_provider_called: false,
        person_identity_analysis_enabled: false,
        raw_video_sent_to_backend: false,
        frames_stored: false,
        sensor_ledger_metadata_only: true,
      },
      camera_state: "disabled",
      preview_state: "manual_opt_in_available",
      recording: false,
      streaming: false,
      snapshot: "disabled",
      vision_analysis: "disabled",
      storage: false,
      provider: "none/not_connected",
      source_endpoint: DASHBOARD_READ_MODEL_ENDPOINT,
      preview_only: true,
      read_only: true,
    },
    raw_audio_recording: {
      state: {
        mode: "browser_local_recorder",
        available: "client_side_unknown_until_browser_loads",
        recording_active: false,
        activation: "explicit_operator_record_button",
        stop_control_required: true,
        download_available_after_stop: true,
        delete_available_after_stop: true,
        backend_upload_enabled: false,
        external_streaming_enabled: false,
        hidden_recording_enabled: false,
      },
      retention: {
        storage: "browser_memory_blob_until_download_or_delete",
        default_retention: "operator_controlled_current_page_session",
        auto_upload: false,
        auto_persist: false,
        delete_revokes_object_url: true,
        operator_must_download_explicitly: true,
      },
      privacy: {
        manual_opt_in_required: true,
        visible_indicator_required: true,
        stop_control_required: true,
        no_backend_upload: true,
        no_provider_call: true,
        no_transcription: true,
        no_always_recording: true,
        no_hidden_recording: true,
      },
      source_endpoint: DASHBOARD_READ_MODEL_ENDPOINT,
      browser_source: "/jarvis/browser-audio-recorder",
      preview_only: false,
      read_only: true,
    },
    memory_brain: {
      state: {
        mode: "visible_read_only_brain",
        outcome_memory_available: false,
        learning_proposals_available: false,
        personal_memory_control_available: false,
        in_memory_only: true,
        compaction_available: false,
        forget_delete_available: "future_gated",
        memory_autoload_enabled: false,
        memory_grants_permission: false,
      },
      entities: [],
      preferences: [],
      decisions: [],
      contradictions: [],
      counts: {
        outcomes: 0,
        failures: 0,
        learning_proposals: 0,
        audit_events: 0,
      },
      why_jarvis_remembers: [
        "JARVIS no tiene memoria personal persistida por defecto.",
        "La memoria nunca concede permisos ni autoriza ejecución.",
      ],
      compaction: {
        status: "contract_only",
        available_now: false,
      },
      forget_delete: {
        status: "future_gated",
        available_now: false,
      },
      safety: {
        sensitive_memory_requires_approval: true,
        no_sensitive_autosave: true,
        no_external_persistence: true,
        memory_is_not_permission: true,
        execution_enabled: false,
      },
      preview_only: false,
      read_only: true,
    },
    local_doctor: {
      state: {
        mode: "read_only_local_doctor",
        backend_reachable: false,
        frontend_build_status: "external_validation_required",
        dashboard_status_endpoint: false,
        event_snapshot_endpoint: false,
        event_stream_endpoint: false,
        hermes_status_endpoint: false,
        local_doctor_endpoint: false,
        browser_stt: "client_side_unknown",
        browser_tts: "client_side_unknown",
        camera_support: "client_side_unknown",
        webgl_support: "client_side_unknown",
      },
      checks: [],
      optional_dependencies: {
        ffmpeg: { available: false, source: "PATH" },
        openwakeword: { available: false, source: "python_importlib" },
      },
      browser_checks: {
        stt: "client_side_unknown",
        tts: "client_side_unknown",
        camera: "client_side_unknown",
        webgl: "client_side_unknown",
        microphone: "client_side_unknown",
      },
      safety: {
        read_only: true,
        no_auto_install: true,
        no_sensor_activation: true,
        no_secret_read: true,
        no_env_dump: true,
        no_hermes_execution: true,
      },
      source_endpoint: "/mark-3/local-doctor/status",
      preview_only: false,
      read_only: true,
    },
    mobile_companion: {
      state: {
        mode: "preview",
        pwa_baseline: "preview",
        mobile_runtime_enabled: false,
        mobile_can_execute: false,
        mobile_can_call_hermes_directly: false,
        mobile_can_approve_real_actions: false,
        mobile_can_reject_real_actions: false,
        mobile_can_modify_scope_real: false,
        mobile_notifications_enabled: false,
        remote_kill_switch_enabled: false,
        remote_camera_enabled: false,
        remote_microphone_enabled: false,
        external_network_required: false,
      },
      mobile_views: ["status", "approvals_preview", "mission_preview", "hermes_visibility", "voice_status", "camera_status", "finance_summary", "kill_switch_preview"].map((id) => ({
        id,
        name: id.replaceAll("_", " "),
        status: "preview",
        can_execute: false,
        can_call_hermes: false,
        notes: "Vista futura read-only; no execute / no Hermes direct.",
      })),
      source_endpoints: [DASHBOARD_READ_MODEL_ENDPOINT],
      preview_only: true,
      read_only: true,
    },
    finance_roi: {
      truth_policy: {
        no_fake_metrics: true,
        unknown_when_no_evidence: true,
        measured_requires_source: true,
        estimated_requires_label: true,
        confirmed_revenue_requires_evidence: true,
        projected_revenue_must_be_labelled: true,
        roi_unknown_without_revenue_and_cost: true,
      },
      metrics: fallbackFinanceMetrics,
      budget: {
        budget_configured: false,
        remaining_budget: UNKNOWN,
        monthly_limit: UNKNOWN,
        alert_threshold: UNKNOWN,
        hard_stop_enabled: false,
        notes: "Budget no configurado; mostrar unknown hasta tener evidencia.",
      },
      source_endpoint: DASHBOARD_READ_MODEL_ENDPOINT,
      preview_only: true,
      read_only: true,
    },
    adaptive_product_builder: {
      state: {
        mode: "preview",
        builder_enabled: "preview/read_only",
        product_generation_enabled: false,
        code_generation_enabled: false,
        deploy_enabled: false,
        stripe_enabled: false,
        landing_publish_enabled: false,
        external_research_enabled: false,
        hermes_dispatch_enabled: false,
      },
      stages: fallbackBuilderStages.map((name) => ({
        name,
        status: name === "Deploy candidate" || name === "Monetización" ? "disabled" : "preview",
        can_execute: false,
        requires_approval: name !== "Idea" && name !== "Validación" && name !== "Blueprint",
        approval_level: "strong",
        evidence_required: "measured_source_before_metric",
        notes: "Stage preview/future-gated/disabled; sin ejecución.",
      })),
      source_endpoint: DASHBOARD_READ_MODEL_ENDPOINT,
      preview_only: true,
      read_only: true,
    },
    frontend_pilot: {
      state: {
        mode: "read_only_pilot",
        dashboard_route: "/jarvis",
        backend_status_endpoint: DASHBOARD_READ_MODEL_ENDPOINT,
        frontend_can_execute: false,
        frontend_can_approve: false,
        frontend_can_activate_sensors: false,
        frontend_can_move_money: false,
        frontend_can_deploy: false,
        frontend_can_send_email: false,
      },
      readiness_checks: ["dashboard_route_exists", "read_model_connected", "finance_roi_visible", "product_builder_visible", "no_frontend_execute", "no_uncontrolled_sensor_activation"].map((name) => ({
        name,
        status: "passed",
        evidence: name,
        notes: "Read-only frontend pilot check.",
      })),
      hardening_notes: {
        npm_audit_vulnerabilities_observed: UNKNOWN,
        npm_audit_fix_not_run: true,
        dependency_hardening_requires_separate_pr: true,
        no_lockfile_changes_expected: true,
        frontend_build_required_before_merge: true,
        full_pytest_required_before_merge: true,
      },
      source_endpoint: DASHBOARD_READ_MODEL_ENDPOINT,
      preview_only: true,
      read_only: true,
    },
    visual_command_center_pilot: {
      state: {
        mode: "read_only_pilot",
        dashboard_route: "/jarvis",
        status_endpoint: DASHBOARD_READ_MODEL_ENDPOINT,
        backend_read_model_connected: false,
        frontend_execution_enabled: false,
        approvals_real_enabled: false,
        hermes_direct_execution_enabled: false,
        voice_real_enabled: true,
        browser_local_voice_loop_enabled: true,
        camera_real_enabled: true,
        raw_audio_recording_enabled: true,
        vision_analysis_enabled: false,
        mobile_runtime_enabled: false,
        money_enabled: false,
        deploy_enabled: false,
        email_enabled: false,
        credentials_enabled: false,
      },
      read_only_checks: ["no_post_put_delete", "no_execute_route", "manual_get_user_media_only", "manual_media_recorder_only", "no_audio_context_capture", "no_camera_snapshot_storage", "no_money_movement", "no_fake_metrics"].map((name) => ({
        name,
        status: "passed",
        evidence: name,
        notes: "Static/read-model guardrail.",
      })),
      source_endpoint: DASHBOARD_READ_MODEL_ENDPOINT,
      preview_only: true,
      read_only: true,
    },
    safety: {
      frontend_can_execute: false,
      frontend_can_approve: false,
      no_auto_execute: true,
      no_frontend_execute: true,
      no_duplicate_hermes_runtime: true,
      no_get_user_media: false,
      no_sensor_activation: false,
      no_uncontrolled_sensor_activation: true,
      no_sensor_activation_on_load: true,
      manual_browser_voice_activation_only: true,
      manual_browser_camera_activation_only: true,
      manual_browser_raw_audio_recording_only: true,
      no_voice_recording: false,
      no_hidden_voice_recording: true,
      no_browser_raw_audio_capture: false,
      no_raw_audio_backend_upload: true,
      no_camera_capture: false,
      no_camera_activation_on_load: true,
      no_camera_snapshot_storage: true,
      no_camera_streaming_to_backend: true,
      no_frontend_tool_runner: true,
      no_tool_call: true,
      no_file_write: true,
      no_network_call: true,
      no_direct_hermes_call_from_mobile: true,
      no_direct_hermes_call_from_voice: true,
      no_direct_hermes_call_from_camera: true,
      no_frontend_hermes_execution: true,
      no_hermes_dispatch: true,
      no_post_put_delete_from_jarvis_page: true,
      no_money_movement: true,
      no_deploy: true,
      no_credentials: true,
      no_email_send: true,
    },
    timeline: [
      {
        event: reason === "loading" ? "dashboard read model loading" : "dashboard read model unavailable",
        source: DASHBOARD_READ_MODEL_ENDPOINT,
        status: reason,
        read_only: true,
      },
    ],
    read_only_contract: {
      aggregated_endpoint: DASHBOARD_READ_MODEL_ENDPOINT,
      allowed_http_methods_for_frontend: ["GET"],
      internal_sources_are_read_only_status_or_audit: true,
      frontend_must_not_call_execute: true,
      frontend_must_not_request_sensor_permissions: false,
      frontend_sensor_permission_scope: "manual browser SpeechRecognition, manual camera preview, manual local raw audio recorder",
      frontend_must_not_request_camera_permissions: false,
      frontend_camera_permission_scope: "manual preview only; no backend stream, no analysis, no storage",
    },
  };
}

export const contractCopyGroups = [
  [
    "Base read-only",
    [
      "Centro de Mando JARVIS",
      "Núcleo de Voz JARVIS",
      "Control de Misión",
      "preview-only",
      "En esta fase no se ejecuta nada",
      "Conversation Preview",
      "Preview conversation",
      "Intent / Risk Preview",
      "Mission Lifecycle",
      "Safety Banner",
      "No auto execute",
      "No Hermes dispatch",
      "No tool call",
      "No file write",
      "No network",
      "No hidden voice recording",
      "No camera activation on load",
      "Wake phrase is not permission",
      "Si una misión necesita algo sensible, aparecerá en Approval Console",
      "Hermes solo ejecutará después de approval válido",
      "El frontend no puede saltarse gates",
      "JARVIS gobierna",
      "Hermes ejecuta",
      "Consola de Aprobación",
      "Hermes Execution",
      "Ejecución Hermes",
      "El frontend no puede ejecutar Hermes directamente",
      "Sin ejecución activa",
      "Capacidades gobernadas",
      "Rutas bloqueadas",
      "Requisitos antes de ejecución futura",
      "approval válido",
      "scope exacto",
      "coste/impacto",
      "operador humano",
      "Kill Switch",
      "KILL SWITCH",
      "No fake metrics",
      "unknown",
      "La cámara no graba por defecto",
      "Mobile es una interfaz, no un runtime",
      "La wake phrase nunca aprueba acciones",
      "La voz puede ser canal de aprobación solo si está autenticada, gateada y auditada",
      "Las acciones sensibles requieren aprobación humana",
      "Las acciones críticas requieren confirmación fuerte",
      "Hermes ejecuta solo bajo gates válidos",
      "No hay ejecución real que detener desde este panel",
      "No hay ejecución real que detener desde esta shell",
      "Preview-only: approval execution is not wired in this PR",
      "Leyenda de riesgo",
      "Nivel 0-1",
      "Nivel 5",
      "Readback / confirmación fuerte",
      "Presence UI",
      "Local System Contract",
      "smart bar",
      "camera preview",
      "raw audio recorder",
      "folded history",
      "barra inteligente inferior",
      "historial plegado",
      "JARVIS runtime/daemon local es el sistema",
      "/jarvis es solo la interfaz visual",
      "móvil y VPS serán clientes/puentes futuros",
      "frontend no ejecuta directamente Hermes",
      "voz local controlada disponible en esta PR",
      "cámara preview y grabación local bajo botón explícito",
      "reactor/orbe cinematográfico",
      "partículas",
      "HUD futurista",
      "reactor de presencia",
    ],
  ],
  [
    "Voice / Wake",
    [
      "No estoy escuchando ni grabando audio",
      "Local Voice Loop",
      "Conversación manual continua",
      "SpeechRecognition / webkitSpeechRecognition",
      "speechSynthesis",
      "selección preferente de voz española",
      "Soporte dependiente del navegador",
      "No always-listening",
      "No wake listener persistente",
      "No audio bruto almacenado",
      "No audio bruto enviado al backend",
      "raw_audio_sent_to_backend=false",
      "approval_by_voice_enabled=false",
      "wake_phrase_approval=false",
      "tono calmado",
      "tono concentrado",
      "tono alerta",
      "tono intenso",
      "Política wake word",
      "Frases soportadas futuras: Hola Jarvis, Jarvis.",
      "La wake phrase no ejecuta acciones",
      "Las acciones críticas requieren readback y confirmación fuerte",
      "Privacidad voz",
      "micrófono: manual bajo botón explícito",
      "conversation_active",
      "wake_listening",
      "recording=false",
      "grabación: false",
      "audio bruto almacenado: false",
      "proveedor de navegador puede variar",
      "background listening",
      "voice approval",
      "La voz puede preparar una intención futura",
      "Si requiere aprobación, aparecerá en Approval Console",
      "Frontend/voice no llama Hermes directamente",
      "Kill Switch voz",
      "Stop cancela escucha y speechSynthesis",
      "JARVIS aún no tiene wake listener persistente real en esta PR; la conversación se activa manualmente. Arquitectura preparada para wake phrase sin grabar ni transcribir todo.",
      "La integración futura deberá cortar wake runtime y ejecución gobernada",
      "Wake Word Local Safe Flow",
      "wake listening sin grabación ni transcripción continua",
      "micrófono hard-off",
      "Hola Jarvis",
      "Jarvis",
      "Stop phrases",
      "Mic hard-off",
      "Wake-word-only",
      "Command listening",
      "Push-to-talk",
      "Typed preview",
      "Hola Jarvis, revisa el estado del proyecto",
      "wake phrase detectada",
      "comando restante",
      "abriría ventana de comando",
      "ejecutaría",
      "aprobaría",
      "llamaría Hermes",
      "La wake phrase solo puede abrir una ventana de comando futura",
      "La aprobación por voz requiere canal autenticado, readback y auditoría",
      "Las acciones críticas requieren doble o triple confirmación",
      "no micrófono always-on",
      "no grabación",
      "no STT persistente",
      "no TTS como approval",
      "no provider backend de audio",
      "no background listener",
      "no Hermes dispatch",
      "no auto execute",
      "offline",
      "online",
      "preview",
      "dormant",
      "dormido",
      "listening_wake_word",
      "listening_command",
      "thinking",
      "speaking",
      "approval_required",
      "hermes_executing",
      "paused",
      "blocked",
      "error",
      "kill_switch",
    ],
  ],
  [
    "Camera / Mobile",
    [
      "Cámara / Visión",
      "Preview local con botón explícito",
      "No se sube vídeo al backend",
      "No hay proveedor externo de visión",
      "La visión futura requerirá permiso explícito y auditoría",
      "La cámara no graba por defecto.",
      "La visión solo se activa con permiso explícito.",
      "Estado actual",
      "permiso solicitado",
      "recording",
      "streaming",
      "snapshot",
      "vision analysis",
      "provider externo",
      "Privacidad",
      "no camera activation on load",
      "manual getUserMedia only",
      "no recording",
      "no snapshot",
      "no image/video storage",
      "explicit operator permission required",
      "visual indicator required",
      "audit required",
      "cámara apagada",
      "permiso requerido",
      "preview futuro",
      "análisis futuro",
      "grabación desactivada",
      "almacenamiento desactivado",
      "Mobile Companion",
      "Mobile no ejecuta acciones",
      "Approvals reales desde móvil quedan future-gated",
      "No se guardan credenciales ni tokens",
      "Mobile no llama a Hermes directamente.",
      "PWA baseline",
      "mobile runtime",
      "approvals reales desde móvil",
      "remote kill switch",
      "mobile camera",
      "mobile microphone",
      "notifications",
      "offline cache",
      "service worker",
      "push",
      "background sync",
      "Estado",
      "Approvals preview",
      "Mission preview",
      "Hermes visibility",
      "Voice status",
      "Camera status",
      "Finance summary",
      "Kill switch preview",
      "no execute",
      "no Hermes direct",
      "no mobile execute",
      "no direct Hermes call",
      "no mobile sensor activation",
      "no real mobile approvals in this PR",
      "approval requires backend gate",
      "critical approval requires strong confirmation",
    ],
  ],
  [
    "Finance / Product / Pilot",
    [
      "Finance / ROI",
      "No fake metrics.",
      "Si no hay evidencia, mostrar unknown.",
      "Revenue confirmado requiere evidencia.",
      "ROI queda unknown sin revenue y costes reales.",
      "No se mueve dinero desde este panel.",
      "Stripe live requiere aprobación fuerte.",
      "coste real",
      "coste estimado",
      "revenue confirmado",
      "revenue proyectado",
      "gross revenue",
      "expenses",
      "net revenue",
      "budget",
      "Product Builder Adaptativo",
      "No es un Template Builder.",
      "Si dos productos parecen clones, el builder ha fallado.",
      "Deploy real requiere aprobación fuerte.",
      "Stripe/checkout real requiere aprobación fuerte.",
      "Revenue real requiere confirmación.",
      "Idea",
      "Validación",
      "Blueprint",
      "Código",
      "Landing",
      "Deploy candidate",
      "Monetización",
      "Medición",
      "preview / future-gated / disabled",
      "Pilot read-only",
      "Frontend Pilot / Hardening",
      "El dashboard mira, no toca.",
      "No POST/PUT/DELETE.",
      "No execute.",
      "No sensores sin activación manual.",
      "Dependency hardening queda para una PR separada.",
      "/jarvis",
      "/mark-3/dashboard/status",
      "finance_roi_visible",
      "product_builder_visible",
      "no_frontend_execute",
      "no_uncontrolled_sensor_activation",
      "npm audit vulnerabilities observed",
      "full pytest required before merge",
      "Visual Command Center Pilot",
      "read-only pilot",
      "No se ejecuta Hermes desde el frontend",
      "No se activan sensores sin control manual explícito",
      "No hay approvals reales en esta fase",
      "No hay métricas falsas",
      "Los valores sin evidencia se muestran como unknown",
      "Checklist de panels",
      "Checklist de seguridad",
      "Estado de botones críticos",
      "Pasos para el operador",
      "Limitaciones conocidas",
      "Header",
      "Voice Core",
      "Raw Audio Recorder",
      "Mission Control",
      "Approval Console",
      "Agent / Module Radar",
      "Camera / Vision",
      "Live Timeline / Audit",
      "no_post_put_delete",
      "no_execute_route",
      "manual_get_user_media_only",
      "manual_media_recorder_only",
      "no_audio_context_capture",
      "no_camera_snapshot_storage",
      "no_money_movement",
      "no_fake_metrics",
      "Detalles en pestañas",
      "modo preview/read-only",
      "max-h-[64vh] overflow-auto",
    ],
  ],
  [
    "External Adoption Contracts",
    [
      "event bus read-only",
      "voice_state",
      "wake_state",
      "tts_state",
      "hermes_state",
      "approval_state",
      "mission_state",
      "camera_state",
      "recording_state",
      "memory_state",
      "risk_state",
      "execution_state",
      "audit_event",
      "Voice Session Manager",
      "wake listening seguro",
      "Hola Jarvis / Jarvis",
      "wake phrase nunca aprueba",
      "cámara real opt-in",
      "indicador visible",
      "stop/cancel",
      "grabación local opt-in",
      "retención",
      "borrado",
      "memoria visible / brain",
      "entidades",
      "decisiones",
      "preferencias",
      "contradicciones",
      "compactación",
      "por qué JARVIS recuerda algo",
      "pairing",
      "revocación",
      "kill switch remoto",
      "Telegram como canal gobernado",
      "local runtime / daemon",
      "installer / doctor",
      "FPS",
      "power save",
      "fallback sin WebGL",
      "Personal OS",
      "rutinas",
      "contexto",
      "familia",
      "daily operator",
    ],
  ],
] as const;
